apiVersion: v1
kind: Secret
metadata:
  name: gmr-smoke-creds
  namespace: gmr
type: Opaque
stringData:
  email: "researcher@gmr.test"
  password: "TestPass123!"
  kuma_push_url_prod: "http://uptime-kuma.uptime-kuma.svc.cluster.local:3001/api/push/gmr-smoke-prod"
  kuma_push_url_dev: "http://uptime-kuma.uptime-kuma.svc.cluster.local:3001/api/push/gmr-smoke-dev"
